# Stellar ağındaki token bilgilerini içerir.

# Genel Organizasyon Bilgileri
[DOCUMENTATION]
ORG_NAME="Turkish Token"
ORG_DBA="TRK Token"
ORG_URL="https://onur5355.github.io/TRK/"
ORG_LOGO="https://onur5355.github.io/TRK/logo.png"
ORG_DESCRIPTION="The official token of TRK on Stellar"
ORG_TWITTER="TRKToken"
ORG_GITHUB="https://github.com/onur5355/TRK"

# Token Bilgileri
[[CURRENCIES]]
code="TurkCoin"
issuer="GCAI4LK7Y4WKXM4P6FCNSRXZCX7AX66C3QE47NLZXBSWCKR2F3362APA"  # Stellar Token Adresi (Değiştir!)
status="live"
display_decimals=2
image="https://onur5355.github.io/TRK/token-icon.png"
